# 线性代数与矩阵论

## 向量及其运算

### 基本概念

In [1]:
# 特征向量

### 基本运算

In [ ]:
# 向量的内积
# 内积为0, 表示正交
# 向量的阿达马积, 对应分量相乘

### 向量的范数

In [2]:
# L1范数
# L2范数
# L-无穷范数 max|x|
# 柯西-施瓦茨不等式, 当且仅当两个向量成比例时, 取等号
# 向量内积等于向量模✖️ cos, 向量之间的夹角大于90度, 内积为负数
# 范数满足三角不等式

### 解析几何

In [3]:
# 超平面方程以及他的法向量
# 点到超平面的距离

### 线性相关性

In [4]:
# 可以线性表达
# 线性相关与线性无关
# 极大线性无关组

### 向量空间

In [5]:
# 线性空间
# 子空间
# 向量的基: 向量空间的极大线性无关组, 基的数量为空间的维数
# 正交基, 标准正交基
# 空间的基和标准正交基都不是唯一的

In [6]:
# 制造标准正交基: 使用格拉姆-施密特正交化

### 应用举例: 线性回归

In [7]:
# 最小化均分误差: MSE
# 目标函数

### 应用举例: 线性分类器与支持向量机

In [8]:
# 怎么理解支撑平面

## 矩阵及其运算

In [9]:
# 对称矩阵 PT = P
# 对角矩阵 只有对角元素有值
# 单位矩阵 
# 正交矩阵 PT P = I 行列向量均为单位向量且相互正交, 构成标准正交基 
# 格拉姆矩阵: 为转置 与其 向量组按列组成的矩阵乘积

### 基本运算

In [10]:
# 转置
# 数乘
# 矩阵相乘
# 矩阵的阿达马积

In [11]:
# 线性方程组的矩阵表示
# 系数矩阵
# 常数向量
# 增广矩阵

In [12]:
# 矩阵乘法的代码实现
import numpy as np
A = np.array([[1, 1, 0], [0, 0, 1]])
B = np.array([[0, 1], [0, 0], [1, 0]])
C = np.dot(A, B)

In [14]:
# 矩阵初等变换
# 实现行或列的乘某个数: 左乘对角, 实现行

In [15]:
# 矩阵乘法不满足交换律

In [16]:
# 矩阵的分块

### 逆矩阵

In [1]:
# 可逆矩阵也称为非奇异矩阵, 不可逆为奇异
# 矩阵可逆, 则其逆矩阵唯一
# 对角矩阵的逆矩阵为对角元素的倒数, 但是对角元素不能为0

In [2]:
# 矩阵的秩
# 定义为线性无关的最大数量
# 矩阵可逆的充要条件是满秩

In [4]:
# 矩阵的初等行变换
# 三种初等行变换对应三种初等矩阵, 以及初等矩阵的逆矩阵
# 对矩阵做初等行变换, 等价于左乘对应的初等矩阵

In [5]:
# 用初等行变换求矩阵的逆矩阵
# P[A I] = [I A-1]

In [7]:
# python实现矩阵的求逆
import numpy as np
A = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 5]])
B = np.linalg.inv(A)
print(B)

[[1.  0.  0. ]
 [0.  1.  0. ]
 [0.  0.  0.2]]


In [11]:
# 正交矩阵
# A AT = AT A = I
# A-1 = AT

In [1]:
# 正交矩阵的行列向量均为单位向量且相互正交, 构成标准正交基
# 正交矩阵的乘积仍然是正交矩阵
# 正交矩阵的逆矩阵仍然是正交矩阵
# 正交矩阵的转置仍然是正交矩阵

### 矩阵的范数

In [14]:
# 诱导范数的几何意义是矩阵所代表的线性变换对向量进行变换后, 向量长度的最大拉伸倍数
# 如果p=2, 则称为谱范数

In [15]:
# 矩阵的F范数
# F范数是谱范数的一个上界

### 应用: 人工神经网络

In [16]:
# 激活函数的作用是什么: 
# 我感觉是为了标准化数据

### 线性变换

In [17]:
# 对于线性空间, 加法和数乘都具有线性关系
# 矩阵乘法就是线性变换
# 旋转变换也是
# 正交变换也是, 它能保持向量的长度不变. 对两个向量变换, 他们之间的角度不变. 对应的矩阵是正交矩阵

In [18]:
# 旋转变换是正交变换, 可以证明旋转变换矩阵是正交矩阵, 所以是正交变换

In [19]:
# 缩放变换也是线性变换

## 行列式

In [21]:
# 二阶和三阶的公式

In [22]:
# 行列式的拉普拉斯(laplace expansion)展开
# 代数余子式

In [23]:
# 行列式具有多线性

In [24]:
# 伴随矩阵: 通过代数余子式的转置构成
# A A* = |A| I
# A-1 = A* / |A| (|A|不等于0)

In [25]:
# |AB| = |A||B|, 如果是尺寸相同

In [26]:
# 正交矩阵的行列式绝对值为1

In [30]:
# python实现行列式的计算
import numpy as np
A = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 5]])
d = np.linalg.det(A)
print(d)

4.999999999999999


In [32]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
d = np.linalg.det(A)
print(d)

-9.51619735392994e-16


## 线性方程组

### 高斯消元法

In [34]:
# 交换方程位置
# 用非0的常数乘以方程两端
# 将一个方程的常数倍加到另一个方程上去

### 齐次方程组

In [35]:
# 判断条件:
# 如果r(A) = n, 方程组只有0解
# 如果r(A) < n, 方程组有非0解, 如果A是方阵, 也就是A不可逆 

In [37]:
# 解的性质与结构
##基础解系: 线性无关且方程组的任意一个解都可以由这组解线性表示
##基础解系包含n-r(A)个解, 他们的线性组合为最终的通解

### 非齐次方程组

In [38]:
# 判定条件:
# 如果r(A) = r(B), 那么方程组的解存在, 并且如果r(A) = n, 那么有唯一解; 如果r(A) < n, 那么有无穷解
# 如果r(A) < r(B), 那么方程组的解不存在

In [39]:
# 解的性质与结构
##基础解系: 齐次方程组的通解 + 非齐次方程组的一个特解

In [40]:
# python实现非齐次方程组
import numpy as np
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)
print(x)

[2. 3.]


## 特征值和特征向量

### 特征值和特征向量

In [42]:
# 特征向量是 经过这个矩阵的线性变换之后仍然处在同一条直线上的向量
# 特征值, 特征向量
# 特征矩阵, 特征方程
# 矩阵的特征多项式

In [44]:
# 对角矩阵的特征值为其主对角线的元素

In [45]:
# 代数重数
# 矩阵的谱: 特征值构成的集合
# 矩阵的谱半径: 所有特征值绝对值的最大值

In [46]:
# 矩阵A不可逆, 则0是它的特征值; 矩阵A可逆, 则0不是他的特征值

In [47]:
# 几何重数
# 特征子空间: 维度为m = n - r(A - xI)

In [48]:
# 对于超过四阶的矩阵, 求解的是高次方程, 并且没有公式解, 只能求近似解

In [50]:
# python实现矩阵的特征值和特征向量
import numpy as np 
A = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 5]])
eigvalues, eigvectors = np.linalg.eig(A)
print(eigvalues)
print(eigvectors)


[1. 1. 5.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [51]:
# 特征值与矩阵的迹以及行列式的关系

In [52]:
# 矩阵迹 是 矩阵特征值的和
# 矩阵的行列式的结果 是 矩阵特征值的积

In [53]:
# 特征值的重要性质
# 1. 矩阵可逆, 逆矩阵的特征值是倒数, 特征向量不变
# 2. 矩阵的n次方的特征值是n次方, 特征值的k倍是k倍
# 3. 特征值的多项式==A的多项式
# 4. A与AT有相同的特征值

In [54]:
# 特征向量的重要性质
# 1. 同一个特征值的特征向量的非0特征组合仍然是关于特征值的特征向量
# 2. 矩阵属于不同特征值的特征向量线性无关
# 3. 实对称矩阵的特征值都是实数
# 4. 共轭计算
# 5. 实对称矩阵属于不同特征值的特征向量相互正交

### 相似变换

In [55]:
# 相似变换, 相似变换矩阵

In [56]:
# 相似矩阵具有相同的特征值

In [59]:
# 矩阵的相似对角化
# P-1 A P = 对角矩阵, P为特征向量的排列, 对角矩阵为特征值. 前提是P可逆, 有n个特征值
# 实对称矩阵一定可以对角化
# n阶实对称矩阵有n个线性无关的特征向量

### 正交变换

In [60]:
# 前提是实对称矩阵
# 实对称矩阵的特征向量已经是正交的, 可以让他们再单位化就可以构成正交矩阵
# 正交矩阵又有A AT = I, 所以PT A P = 对角矩阵

In [2]:
# 正交变换可以保证矩阵的对称性, P是正交矩阵, A是对称矩阵y
# 两种正交变换, 一种是正交矩阵, 一种是正交以及对称矩阵

In [4]:
# HouseHolder变换
##Householder矩阵
##对称三对角矩阵
##上海森堡矩阵

### QR算法

In [5]:
# 对于一个矩阵A, QR分解将其化为一个正交矩阵Q与一个上三角矩阵R的乘积

In [6]:
# A是迭代的, 并且一直是相似变换

In [7]:
# 因为QR迭代是正交变换, 所以A如果是对称矩阵的话, 保证对称性, 收敛到上三角, 最终为对角矩阵
# 并且所有正交矩阵Q的乘积的所有列是A的特征向量

In [9]:
# 带移位的QR算法
# 移位系数
# A的迭代仍然的相似的

### 广义特征值

In [10]:
# Ax = 特征值Bx

### 瑞利商

In [11]:
# 瑞利商的最小值为最小特征值, 最大值为最大特征值
# 当x分别为最小大特征值对应的特征向量的时候取到这两个值

In [12]:
# 增加x为单位向量之后, 瑞利商变为唯一解
# R = xT A x
# 瑞利商的所有极值在特征值与特征向量处取到, 且在最大特征值处, 瑞利商有最大值

In [13]:
# 广义瑞利商
##广义瑞利商的所有极值在广义特征值处取到.

### 谱范数与特征值的关系

In [16]:
# 矩阵的谱范数等于WT W的最大特征值的平方根, 即W最大的奇异值
# 奇异值是WT W特征值的平方根

In [17]:
# 谱范数的平方, 就是求瑞利商的极大值, 于是他的解是矩阵WT W的最大特征值, 于是求他的平方根

In [18]:
# python实现求矩阵的范数
import numpy as np
A = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
n = np.linalg.norm(A, ord=2)
print(n)

22.40929816327044


### 条件数

In [19]:
# 定义为它的范数与它的逆矩阵范数的乘积 cond(W) = ||W|| ||W-1||

In [21]:
# 如果使用的是谱范数, 那么||W||等于W的最大奇异值, ||W-1||等于W的最小奇异值的逆
# 也就是说此时条件数为矩阵的最大特征值和最小特征值的比值 cond(W) >= 1

In [22]:
# 条件数决定了矩阵的稳定性, 条件数越大, 越接近不可逆矩阵

In [23]:
# python实现求条件数
A = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 5]])
c = np.linalg.cond(A)
print(c)

5.0


### 应用: 谱归一化与谱正则化

In [24]:
# 正则化: 较少过拟合, 迫使模型的参数值很小, 使模型可以泛化.
# 具体的做法: 在目标函数中添加正则化项, 通常为参数向量的L1范数或者L2范数

In [ ]:
# 谱正则化: 利用谱范数构造正则化项
# 谱归一化: 将权重矩阵除以谱范数, 那么再计算谱范数则等于1
# 利用幂迭代法计算谱范数

In [26]:
# 李普希茨条件: 权重矩阵的谱范数存在一个较小的上界值, 那么该神经网络的映射有较小的利普希茨常数

In [27]:
# 谱正则化
##为了使得具有较小的利普希茨常数, 所以需要有较小的谱范数
##构建所有权重矩阵的谱范数平方之和

## 二次型

### 基本概念

In [ ]:
# 实对称矩阵与二次型一一对应

### 正定二次型与正定矩阵

In [29]:
# 正定二次型: 一个二次型对于任意非0向量x取值都大于0
# 正定矩阵: 使得二次型任意x非0取值都大于0的矩阵

In [30]:
# 半正定矩阵: 使得二次型任意x非0取值都大于等于0的矩阵
# 负定矩阵
# 不定矩阵: 不能保证大于或小于0

In [31]:
# 正定矩阵的所有主对角线元素都大于0

In [32]:
# 除了定义法的证明
# 第二种: A的n个特征值大于0
        # 存在可逆矩阵P使得A = PT P
        # 如果A是正定的, 那么AT也是正定的
        # A的所有顺序主子式是均为正        

In [33]:
# 对于任意的矩阵A, AT A是对称半正定矩阵

In [34]:
# 实对称矩阵负定的证明:
##矩阵A的n个特征值都小于0
##存在可逆矩阵P使得A = -PT P
##矩阵A的所有奇数阶顺序主子式均为负, 偶数阶顺序主子式均为正

### 标准型

In [35]:
# 就是二次型由纯平方项构成

In [37]:
# 标准型对应的矩阵是对角矩阵
# 正平方项的数量为正惯性指数 负的是负惯性指数

In [38]:
# 二次型的矩阵是对称矩阵, 一定可以对角化, 标准化

In [39]:
# A = P 对角矩阵 PT
# 如果矩阵A的n个特征值都是大于0, 则对角矩阵一定正定

## 矩阵分解

### 楚列斯基分解

In [40]:
# n阶对称半正定矩阵A, Cholesky分解 A = L LT, L为下三角矩阵
# 如果是正定矩阵, 则分解唯一

In [43]:
# 利用Cholesky矩阵进行线性方程组求解
# Ax = b, 如果A是正定矩阵
# L LTx = b 
# L y = b 和 LT x = y

In [44]:
# 楚列斯基分解可以检测矩阵的半正定性
# 楚列斯基的计算公式

In [51]:
# python实现楚列斯基分解
import numpy as np 
A = np.array([[6, 3, 4, 8], [3, 6, 5, 1], [4, 5, 10, 7], [8, 1, 7, 25]])
L = np.linalg.cholesky(A)
print(L)
B = np.dot(L, L.T)

[[ 2.44948974  0.          0.          0.        ]
 [ 1.22474487  2.12132034  0.          0.        ]
 [ 1.63299316  1.41421356  2.30940108  0.        ]
 [ 3.26598632 -1.41421356  1.58771324  3.13249102]]


### QR分解

In [1]:
# A = QR

In [2]:
# A是方阵
# 如果矩阵A可逆且要求矩阵R的主对角元素为正的
# 如果A有m个线性无关的列, 则Q的前m个列构成A的列空间的标准正交基

In [4]:
# A不是方阵

In [6]:
# QR分解的三种方式: 格拉姆-施密特正交化, 豪斯霍尔德变换, 吉文斯旋转

In [8]:
# 格拉姆-施密特正交化
# 1. 使用施密特正交化将矩阵A列正交化单位化
# 2. 再求得上三角矩阵

In [9]:
# HouseHolder变换

In [11]:
# 利用python实现QR分解
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Q, R = np.linalg.qr(A)
print(Q)
print(R)

[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.11164740e-15]]


In [13]:
import numpy as np 
A = np.array([[1, 2, 3], [4, 5, 6]])
Q, R = np.linalg.qr(A)
print(Q)
print(R)

[[-0.24253563 -0.9701425 ]
 [-0.9701425   0.24253563]]
[[-4.12310563 -5.33578375 -6.54846188]
 [ 0.         -0.72760688 -1.45521375]]


### 特征值分解

In [ ]:
# n阶矩阵可以特征值分解的充要条件是, 他有n个线性无关的特征向量

In [14]:
# 特征值分解可以用来求解矩阵的逆矩阵
# A-1 = Q V-1 Q-1

In [15]:
# 特征值分解可以用来计算矩阵的多项式或者幂
# 对角矩阵的幂仍然是对角矩阵, 是主对角线元素分别求幂

In [ ]:
# 如果A是实对称矩阵
## 那么特征向量可以正交化
## 特征值分解为  A = Q V QT, Q是正交矩阵, 他的列是正交化特征向量

In [16]:
# 使用python实现特征值分解
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
V, U = np.linalg.eig(A)
print(V)  # 特征值
print(U)  # 特征向量

[ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


### 奇异值分解

In [17]:
# 奇异值分解(SVD)是对特征值分解的推广
# SVD是对A AT和AT A进行特征值分解, 因为A AT是对称半正定矩阵, 一定可以特征值分解(对称矩阵)
# UT A V = E
# U的列为A的左奇异向量, AAT的特征向量; V的行为A的右奇异向量, ATA的特征向量
# U, V都是正交矩阵, 因为是实对称矩阵的特征向量

In [ ]:
# 矩阵的奇异值分解: A = U E VT

In [18]:
# AAT和ATA有相同的非0特征值, 但有不同的特征向量
# AAT的特征向量是x, ATA的特征向量是ATx
# ATA的特征向量是x, AAT的特征向量是Ax
# AAT的0特征值不一定是ATA的0特征值

In [19]:
# 奇异值: AAT的特征值的非负平方根是A的奇异值

In [20]:
# ATA的特征值分解: AAT = V ET E VT = V E2 VT
# AAT也是类似的

In [21]:
# 如果A的对称矩阵, 那么AAT = ATA = AA
# 并且AA的特征值是A特征值的平方, A的奇异值为其特征值的绝对值

In [25]:
# python实现SVD分解
import numpy as np 
data = np.array([[1, 2, 3], [4, 5, 6]])
u, sigma, vt = np.linalg.svd(data)
print(u)  # A = u xx vt
print(sigma) # sigma是所有的非0奇异值
print(vt)

[[-0.3863177   0.92236578]
 [-0.92236578 -0.3863177 ]]
[9.508032   0.77286964]
[[-0.42866713 -0.56630692 -0.7039467 ]
 [-0.80596391 -0.11238241  0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]


In [28]:
# 奇异值分解的几何意义
## 对矩阵A的线性变换其实是先旋转变换, 后拉伸变换, 再旋转变换